StolkLaurenGradeCalculator/Models/GradeCalculatorModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace StolkLaurenGradeCalculator.Models
{
    public class GradeCalculatorModel
    {
            [Required]
            [Range(0, 100,
            ErrorMessage = "Assignment grade must be between {1} and {2}.")]
            public int assignment { get; set; }

            [Required]
            [Range(0, 100,
            ErrorMessage = "Group Project grade must be between {1} and {2}.")]
            public int groupProject { get; set; }

            [Required]
            [Range(0, 100,
            ErrorMessage = "Quiz grade must be between {1} and {2}.")]
            public int quiz { get; set; }

            [Required]
            [Range(0, 100,
            ErrorMessage = "Exam grade must be between {1} and {2}.")]
            public int exam { get; set; }

            [Required]
            [Range(0, 100,
            ErrorMessage = "INTEX grade must be between {1} and {2}.")]
            public int intex { get; set; }
    }
}

StolkLaurenGradeCalculator/Controllers/BlahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StolkLaurenGradeCalculator.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace StolkLaurenGradeCalculator.Controllers
{
    public class BlahController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

StolkLaurenGradeCalculator/Views/Blah/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "The Dreaded Grade Calculator";
}

@model GradeCalculatorModel;

<h2>Grade Calculator</h2>
<h3>Enter the percentage for each grade category.</h3>
<form  method="post">
    <label>Assignments</label>
    <input id="assignment" asp-for="assignment" /><br />

    <label>Group Project</label>
    <input id="groupProject" asp-for="groupProject" /><br />

    <label>Quizzes</label>
    <input id="quiz" asp-for="quiz" /><br />

    <label>Exams</label>
    <input id="exam" asp-for="exam" /><br />

    <label>INTEX</label>
    <input id="intex" asp-for="intex" /><br />

    <input id="btnSend" type="submit" value="Submit Grades" />

    <div asp-validation-summary="All"></div>
</form>


<script src="~/js/GradeCalculator.js"></script>

StolkLaurenGradeCalculator/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Lauren Stolk's Bangin Website";
}

<header>
    <h1>Lauren Stolk</h1>
</header>

<img id="myPhoto" src="img/MeWithDog.png" width="300px" />


<p>
    In IS413, I hope to be a better problem solver when it comes to coding. I want to become more familiar with
    languages. I also want to make new friends and learn more than just IS concepts from our professors. I always
    look forward to the Spirit that I feel when I hear my teachers bear testimony in class.
</p>

<ol>
    <li>Cybersecurity Consultant</li>
    <li>Project Manager/Scrum Master</li>
    <li>Back-End Software Developer</li>
</ol>

StolkLaurenGradeCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />

    <!--these two lines make the website icon on the tab in the browser-->
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="~/img/favicon.ico" type="image/ico" />

    <title>@ViewData["Title"]</title>

    <!--<link href="css/default.css" rel="stylesheet" />-->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />

    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>

    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>

</head>

<body>

    <div>
        @RenderBody()
    </div>

    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    

</body>

</html>